[build]
  publish = "./examples/gatsby-theme-blog/public"
  command = "yarn blogBuild"

[build.environment]
  YARN_VERSION = "1.22.4"
  NODE_VERSION = "13.5.0"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_OPTIONS = "--max_old_space_size=4096"